### ISSUE TITLE
Replace `entityManager.createQuery` with `entityManager.find` in `***.findByPk` methods

### ISSUE THREAD

**Issue by Ingvord** [scientific-software-hub/mxhub-ispyb#26]
E.g.

```java
if(!fetchSamples)
	return entityManager.find(Container3VO.class, pk);
```

in `Container3ServiceBean.findByPk`

**Comment by HelgaMond** [comment]
EntityManager (OpenJPA manager) has its own "find" method. So we are using it for better management and search for entities in the relational database.

**Comment by HelgaMond** [comment]
Done. 
Most "findByPk" methods have 1 parameter - pk. But some of them have >1 parameters. These methods' signatures were left without changes.
